linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
  gosec:
    excludes:
      - G601 # false positive since Go 1.22
  varnamelen:
    ignore-names:
      - tc # https://dave.cheney.net/2019/05/07/prefer-table-driven-tests

linters:
  enable:
    - errcheck # default
    - gosimple # default
    - govet # default
    - ineffassign # default
    - staticcheck # default
    - unused # default
    - depguard
    - errname
    - exhaustive
    - funlen
    - gomnd
    - gosec
    - ireturn
    - lll
    - nilerr
    - unparam
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
