version: "2"

linters:
  exclusions:
    paths:
      - examples/
  enable:
    - errcheck # default
    - govet # default
    - ineffassign # default
    - staticcheck # default (includes gosimple checks in v2)
    - unused # default
    - depguard
    - errname
    - exhaustive
    - funlen
    - mnd
    - gosec
    - ireturn
    - lll
    - nilerr
    - unparam
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl_v5
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      enable-all: true
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/ryeguard/ddbcalc
            - github.com/aws/aws-sdk-go-v2
    gosec:
      excludes:
        - G601 # false positive since Go 1.22
        - G304 # CLI tool designed to open user-specified files
    varnamelen:
      max-distance: 6
      ignore-names:
        - tc # https://dave.cheney.net/2019/05/07/prefer-table-driven-tests
