linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
  varnamelen:
    ignore-names:
      - tc # https://dave.cheney.net/2019/05/07/prefer-table-driven-tests

linters:
  enable-all: true
  disable:
    - forbidigo
    - gofumpt
    - deadcode # Deprecated
    - exhaustivestruct # Deprecated
    - golint # Deprecated
    - ifshort # Deprecated
    - interfacer # Deprecated
    - maligned # Deprecated
    - nosnakecase # Deprecated
    - scopelint # Deprecated
    - structcheck # Deprecated
    - varcheck # Deprecated
